FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y # && apt-get upgrade -y
RUN apt-get install python3 python3-pip git build-essential cmake ffmpeg libsm6 libxext6 -y

COPY . /opt/edgedroid
WORKDIR /opt/edgedroid

RUN pip install ".[load-client]"
RUN mkdir -p /edgedroid

WORKDIR /edgedroid
RUN edgedroid-tools --verbose prefetch-all-traces --yes
ENTRYPOINT ["edgedroid-client"]

