FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y #  && apt-get upgrade -y
RUN apt-get install python3 python3-pip git build-essential cmake ffmpeg libsm6 libxext6 -y

RUN pip install dlib